version: '2'

services:

  web:
    container_name: 'aspnetcoreapp'
    image: 'aspnetcoreapp'
    build:
      context: .
      dockerfile: aspnetcore.development.dockerfile
    volumes:
      - .:/var/www/aspnetcoreapp
    ports:
     - "5000:5000"
    depends_on:
     - "postgres"
    networks:
      - aspnetcoreapp-network

  postgres:
    container_name: 'postgres'
    image: postgres
    ports:
     - "5432:5432"
    volumes:
     - ./postgres-data:/var/lib/postgresql/data 
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - aspnetcoreapp-network

networks:
  aspnetcoreapp-network:
    driver: bridge


